### ISSUE TITLE
Err: next_pow_two

### ISSUE THREAD

**Issue by suiwater** [starkware-libs/stwo#451]
https://github.com/starkware-libs/stwo/blob/7612fc7b83513d80602697539344adb6842d3293/src/math/utils.rs#L18-L20
if usize 64
when n = 2.pow(63) + 1
log2_ceil(n)=64
2.pow(64)
/library/core/src/num/uint_macros.rs:1988:24

**Comment by shaharsamocha7** [comment]
Thanks!
Actually we don't need this function:
https://reviewable.io/reviews/starkware-libs/stwo/465#-
